### ISSUE TITLE
About writing the frames to memory

### ISSUE THREAD

**Issue by mayhair** [ArdenButterfield/stammer#25]
I agree that it will save a lot of disk space and allow faster writing of the frames.
One of the reasons you said to use it is because modern computers have plenty of RAM. This makes sense for short videos such as "Steamed Hams". However, it makes less sense for longer ones.
For example, I made a [video](https://www.youtube.com/watch?v=yehGuaevY5w) with this script from a ~2.5 GB 720p copy of "Bee Movie". Uncompressed and lossless image/video formats take up a lot of space, and even with the frames being in the compressed PNG format, the frames totalled around 126 GB (127 GB on disk). For perspective, the computer with which I generated the video has 32 GB of RAM.

How will this problem be addressed? I suspect that a mix of using the actual RAM and writing to disk (maybe via a page file?) could be used. I also believe that once the frames needed to build the video are chosen, the useless ones can be immediately deleted before the build starts.

**Comment by mayhair** [comment]
Closing as I just realised my response would fit better as a comment under #11.

**Comment by PatoFlamejanteTV** [comment]
uhh, just slice your _~**2.5 GB** 720p copy of "Bee Movie"_ to some files and done, btw i think 10 minutes is sufficient for Stammer.
