### ISSUE TITLE
Output file help??

### ISSUE THREAD

**Issue by composition-cassidy** [ArdenButterfield/stammer#28]
I'm confused.. I'm inputting "python stammer.py boot adventures.mp4 futurama.mp4 C:\Users\User\Desktop\Folders\stammer-main\boot.mp4" and it's saying it's an unrecognized argument.. what do I do

![image](https://user-images.githubusercontent.com/99601533/226845765-152ae738-426b-4f08-9516-d681314911c4.png)

**Comment by avydrado** [comment]
put path in " " becouse it has spaces
