### ISSUE TITLE
Make frame-length an optional argument instead of hardcoding

### ISSUE THREAD

**Issue by optionboom** [ArdenButterfield/stammer#37]
Using long frame-lengths for stammer results in a more YTP-style output, compared to the static-like output at short frame-lengths. Making frame-length an argument would increase usability.

I implemented this on my copy, can make a pull request if this is judged to be a good idea.

**Comment by ArdenButterfield** [comment]
That sounds great! I like that idea a lot.

**Comment by optionboom** [comment]
My previous implementation is from before argparser was being used, and also upon testing doesn't work for video, only audio. So I cannot make a PR yet. I'll work on it.

**Comment by Firepal** [comment]
This can be closed now
