### ISSUE TITLE
Combination mode not working

### ISSUE THREAD

**Issue by optionboom** [ArdenButterfield/stammer#46]
Tested with carrier as video and modulator as audio. Not sure exactly what the problem is.

Traceback:
  File "C:\stammer\audio_matching.py", line 74, in make_output_audio

    output_audio = self.build_output_audio()

                   ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\stammer\audio_matching.py", line 169, in build_output_audio

    output_audio[i*self.samples_per_frame : i*self.samples_per_frame + self.samples_per_frame*2] += composed_frame

numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('O') to dtype('float64') with casting rule 'same_kind'`

**Comment by ArdenButterfield** [comment]
Thank you for letting us know! Sorry about that. I believe I have patched the bug. If you are still getting the issue with the most recent version of the code, please let me know.

**Comment by optionboom** [comment]
No longer getting this specific issue, so I'll close it.
