### ISSUE TITLE
Not enough RAM?

### ISSUE THREAD

**Issue by Nazarennno** [ArdenButterfield/stammer#85]
I was finally about to test Stammer when this happened:

usage: stammer.py [-h] [--custom-frame-length CUSTOM_FRAME_LENGTH]
                  [-vm {disk,mem_decay}] [-mcf MIN_CACHED_FRAMES]
                  [-c {8fast,8full,full}] [-m {basic,combination,unique}]
                  carrier_track modulator_track output_file
stammer.py: error: unrecognized arguments: <bebylatte.mp4>

And one of the code errors was the "disk,mem_decay" one and I think it's an indicator for low memory or not?

**Comment by Firepal** [comment]
That's the usage text, explaining what you can tell stammer to do. Specifically where you want video frames to be written, either on disk, or in RAM with a cache that removes copied frames of the video that aren't used. Hence "decayed".

Your computer is unharmed! :]
