### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MichaelJohnny2** [ArdenButterfield/stammer#88]
When I put the carrier track filename
on the terminal, it doesn't find it even though it exists

**Comment by Firepal** [comment]
If it's not in the stammer folder, you have to put the entire path, and in " <- quotes.

**Comment by PatoFlamejanteTV** [comment]
Try dragging the file top the terminal, btw are you on Linux? Mac? Windows? can yo please go to your terminal and type `python --version` please? That could help a lot.


https://github.com/user-attachments/assets/0dfa555b-2aee-49da-9c61-5a22cc567dac
